import {
  Award,
  BadgeCheck,
  BarChart3,
  Bell,
  Bot,
  BookOpen,
  Briefcase,
  BriefcaseBusiness,
  Building,
  Building2,
  Calendar,
  ClipboardList,
  Compass,
  FileBadge,
  FileCheck,
  FileSearch,
  FileText,
  FolderKanban,
  Gauge,
  GraduationCap,
  type LucideIcon,
  LayoutDashboard,
  LayoutTemplate,
  Medal,
  MessageCircle,
  Mic,
  Network,
  ScrollText,
  Send,
  Settings,
  Sparkles,
  Trophy,
  TrendingUp,
  User,
  UserCog,
  UserRound,
  UserSquare,
  Users,
  UsersRound,
  HelpCircle,
} from "lucide-react";

/**
 * Resolves every semantic icon name used in navRegistry.ts (see F5) to
 * a real lucide-react component — kept as a separate, explicit map
 * rather than a dynamic `Icons[name]` lookup, so a typo in navRegistry
 * fails loudly (falls back to HelpCircle, never a blank/broken icon).
 */
export const iconMap: Record<string, LucideIcon> = {
  user: User,
  "layout-dashboard": LayoutDashboard,
  "clipboard-list": ClipboardList,
  "file-check": FileCheck,
  users: Users,
  calendar: Calendar,
  trophy: Trophy,
  award: Award,
  "file-badge": FileBadge,
  "graduation-cap": GraduationCap,
  bell: Bell,
  "message-circle": MessageCircle,
  sparkles: Sparkles,
  "folder-kanban": FolderKanban,
  briefcase: Briefcase,
  "book-open": BookOpen,
  "badge-check": BadgeCheck,
  medal: Medal,
  "user-square": UserSquare,
  "file-text": FileText,
  "building-2": Building2,
  "briefcase-business": BriefcaseBusiness,
  send: Send,
  bot: Bot,
  "file-search": FileSearch,
  gauge: Gauge,
  compass: Compass,
  mic: Mic,
  "bar-chart-3": BarChart3,
  "user-cog": UserCog,
  building: Building,
  settings: Settings,
  "scroll-text": ScrollText,
  network: Network,
  "user-round": UserRound,
  "users-round": UsersRound,
  "trending-up": TrendingUp,
  "layout-template": LayoutTemplate,
};

export function resolveIcon(name: string): LucideIcon {
  return iconMap[name] ?? HelpCircle;
}
