export enum FacultyDesignation {

    PROFESSOR = "PROFESSOR",

    ASSOCIATE_PROFESSOR = "ASSOCIATE_PROFESSOR",

    ASSISTANT_PROFESSOR = "ASSISTANT_PROFESSOR",

    LECTURER = "LECTURER",

    HOD = "HOD"

}