import { Gauge, Sparkles, Map, Trophy, FileText, UserCheck, Medal } from "lucide-react";

import { Card, CardContent, CardHeader, CardTitle } from "@/shared/components/Card";
import { StatCard } from "@/shared/components/StatCard";
import { ErrorState } from "@/shared/components/ErrorState";
import { SkeletonLoader } from "@/shared/components/SkeletonLoader";
import { PageAtmosphere } from "@/shared/components/PageAtmosphere";
import { LevelProgressRing } from "@/shared/components/LevelProgressRing";

import { useCareerScore } from "@/features/career-score/hooks/useCareerScore";

export function CareerScorePage() {
  const { data: score, isLoading, isError, error, refetch } = useCareerScore();

  if (isError) {
    return <ErrorState error={error} onRetry={() => refetch()} />;
  }

  return (
    <div className="relative mx-auto flex max-w-xl flex-col gap-6">
      <PageAtmosphere variant="arcane-grid" />

      <h1 className="flex items-center gap-2 font-display text-2xl font-semibold text-foreground">
        <Gauge className="h-6 w-6 text-primary" aria-hidden="true" />
        Career Score
      </h1>

      {isLoading || !score ? (
        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {Array.from({ length: 5 }).map((_, i) => (
            <SkeletonLoader key={i} className="h-28" />
          ))}
        </div>
      ) : (
        <>
          <Card className="overflow-hidden border-primary/20 bg-gradient-to-br from-primary/5 via-card to-card">
            <CardContent className="flex flex-col items-center gap-3 p-8 text-center">
              <LevelProgressRing level={score.careerScore} progress={score.careerScore / 100} size={128} label="Score" />
              <p className="font-display text-lg font-medium text-primary">
                {score.label}
                <span className="ml-1 text-sm font-normal text-muted-foreground">/ 100</span>
              </p>
            </CardContent>
          </Card>

          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
            <StatCard label="Leaderboard" value={score.leaderboardScore} icon={Trophy} />
            <StatCard label="Resume" value={score.resumeScore} icon={FileText} />
            <StatCard
              label="Profile Completeness"
              value={score.profileCompletenessScore}
              icon={UserCheck}
            />
            <StatCard label="Achievements" value={score.achievementsScore} icon={Medal} />
          </div>

          <p className="font-body text-xs text-muted-foreground">
            The score and label above are computed deterministically from your real Leaderboard
            standing, Resume score, profile completeness, and verified achievements. The narrative,
            recommendations, and roadmap below are generated by RyuZen's AI assistant based on
            those real scores.
          </p>

          <Card>
            <CardHeader>
              <CardTitle>Narrative</CardTitle>
            </CardHeader>
            <CardContent>
              <p className="font-body text-sm text-muted-foreground">{score.narrative}</p>
            </CardContent>
          </Card>

          {score.recommendations.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Sparkles className="h-4 w-4 text-primary" aria-hidden="true" />
                  Recommendations
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ul className="flex flex-col gap-1 font-body text-sm text-foreground">
                  {score.recommendations.map((recommendation) => (
                    <li key={recommendation}>• {recommendation}</li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          )}

          {score.roadmap.length > 0 && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Map className="h-4 w-4 text-primary" aria-hidden="true" />
                  Roadmap
                </CardTitle>
              </CardHeader>
              <CardContent>
                <ol className="flex flex-col gap-1.5 font-body text-sm text-foreground">
                  {score.roadmap.map((step, i) => (
                    <li key={step} className="flex gap-2">
                      <span className="font-display font-bold text-primary">{i + 1}.</span>
                      {step}
                    </li>
                  ))}
                </ol>
              </CardContent>
            </Card>
          )}
        </>
      )}
    </div>
  );
}
