import { AIChatModel } from "../../src/domains/ai/chat/infrastructure/persistence/AIChatModel.js";

import { pick, pickMany, randomInt } from "../utils/random.js";
import type { SeededStudent } from "../types.js";

/**
 * Real, pre-written conversation pairs - deliberately NOT generated by
 * calling the live AI provider during seeding. Seed data should be
 * fast, deterministic, and not depend on a live external API call
 * (which could be slow, rate-limited, or unavailable) - this seeds
 * the same real AIChatModel shape the live SendAIChatMessageUseCase
 * writes to, just with realistic fixed content instead of a live
 * generation, so the chat UI has real conversations to render and
 * test against.
 */
const SAMPLE_CONVERSATIONS: { user: string; assistant: string }[][] = [
  [
    {
      user: "What activities can I still join this semester?",
      assistant:
        "Based on your department and semester, you have a few open activities right now. Check the Activities tab for the full list with deadlines - I'd recommend starting with ones closing soonest.",
    },
    {
      user: "Which one gives the most points?",
      assistant: "Points vary by activity - hackathons and workshops tend to award more than quizzes. Sort by points on the Activities page to compare them directly.",
    },
  ],
  [
    {
      user: "Am I eligible for the Software Engineer drive?",
      assistant:
        "Eligibility depends on your department, CGPA, and semester matching the drive's real criteria. Check the drive's eligibility section on its detail page - if you meet all the listed requirements, the Apply button will be active.",
    },
  ],
  [
    {
      user: "How can I improve my career score?",
      assistant:
        "Your career score combines your leaderboard standing, resume quality, profile completeness, and verified achievements. Completing more activities, keeping your resume updated, and getting achievements verified by faculty all help.",
    },
    {
      user: "What's a good CGPA to aim for placements?",
      assistant: "Most drives on this platform set a minimum CGPA between 6 and 7.5. Aiming above 7.5 keeps you eligible for nearly every drive that opens.",
    },
  ],
  [
    {
      user: "Can you help me prep for a technical interview?",
      assistant:
        "Sure - try a mock interview under the AI tab to practice with real questions and get scored feedback. For technical rounds specifically, review data structures, your strongest project's architecture, and be ready to explain trade-offs you made.",
    },
  ],
];

export async function seedAiChats(students: SeededStudent[]): Promise<void> {
  const chattingStudents = pickMany(students, Math.min(Math.ceil(students.length * 0.4), students.length));
  let created = 0;

  for (const student of chattingStudents) {
    const conversation = pick(SAMPLE_CONVERSATIONS);
    const messages: { role: string; content: string; timestamp: Date }[] = [];

    let timestamp = new Date(Date.now() - randomInt(1, 10) * 24 * 60 * 60 * 1000);

    for (const turn of conversation) {
      messages.push({ role: "USER", content: turn.user, timestamp });
      timestamp = new Date(timestamp.getTime() + 30 * 1000);
      messages.push({ role: "ASSISTANT", content: turn.assistant, timestamp });
      timestamp = new Date(timestamp.getTime() + randomInt(1, 5) * 60 * 1000);
    }

    await AIChatModel.create({
      userId: student.userId,
      messages,
    });

    created++;
  }

  console.log(`Seed: created ${created} AI chat sessions`);
}
