import { createHash } from "node:crypto";

import { IResumeReviewProvider } from "../../application/ports/IResumeReviewProvider.js";
import { ResumeReviewInput } from "../../application/ports/ResumeReviewInput.js";
import { ResumeReviewResult } from "../../application/ports/ResumeReviewResult.js";

import { GeminiClient } from "../../../../../shared/infrastructure/ai/GeminiClient.js";

import { ReviewSchema, computeResumeScore, buildResumeReviewPrompt } from "./resumeReviewPrompts.js";

/*
 Real Gemini-backed resume review - the cloud counterpart to
 OllamaResumeReviewProvider, sharing the exact same deterministic score
 formula and prompt/schema (resumeReviewPrompts.ts) so a resume's score
 never changes depending on which provider is configured.

 Cache key is namespaced "gemini" (not shared with Ollama's cache
 entries) - switching AI_PROVIDER should not silently serve a cached
 result generated by the other provider.
*/

export class GeminiResumeReviewProvider implements IResumeReviewProvider {
    async review(input: ResumeReviewInput): Promise<ResumeReviewResult> {
        const score = computeResumeScore(input);
        const prompt = buildResumeReviewPrompt(input, score);

        const cacheKey =
            "resume-review:gemini:" +
            createHash("sha256")
                .update(JSON.stringify(input))
                .digest("hex");

        const { strengths, improvements, summary } =
            await GeminiClient.generateJson(prompt, ReviewSchema, {
                cacheKey,
                cacheTtlSeconds: 300
            });

        return { score, strengths, improvements, summary };
    }
}
