import express, { Express } from "express";

import { bootstrap } from "./bootstrap/index.js";
import { errorHandler } from "./shared/core/http/index.js";
import { notFound } from "./shared/core/middleware/notFound.js";

import authRoutes from "../src/domains/identity/presentation/routes/auth.routes.js";
import userRoutes from "./domains/identity/presentation/routes/user.routes.js";
import invitationRoutes from "./domains/identity/presentation/routes/invitation.routes.js";
import organizationRoutes from "./domains/organizations/presentation/routes/organization.routes.js";
import organizationSettingsRoutes from "./domains/organizations/presentation/routes/organization-settings.routes.js";
import activityRoutes from "./domains/academic/activities/presentation/routes/activity.routes.js";
import submissionRoutes from "./domains/academic/submissions/presentation/routes/submission.routes.js";
import auditLogRoutes from "./domains/platform/audit/presentation/routes/audit-log.routes.js";
import departmentRoutes from "./domains/academic/departments/presentation/routes/department.routes.js";
import facultyRoutes from "./domains/academic/faculty/presentation/routes/faculty.routes.js";
import studentRoutes from "./domains/academic/students/presentation/routes/student.routes.js";
import alumniRoutes from "./domains/academic/alumni/presentation/routes/alumni.routes.js";
import mentorshipRoutes from "./domains/academic/mentorship/presentation/routes/mentorship.routes.js";
import clubRoutes from "./domains/campus/clubs/presentation/routes/club.routes.js";
import eventRoutes from "./domains/campus/events/presentation/routes/event.routes.js";
import leaderboardRoutes from "./domains/campus/leaderboard/presentation/routes/leaderboard.routes.js";
import pointLedgerRoutes from "./domains/campus/point-ledger/presentation/routes/point-ledger.routes.js";
import aiProviderStatusRoutes from "./domains/ai/provider-status/presentation/routes/ai-provider-status.routes.js";
import badgeRoutes from "./domains/campus/badges/presentation/routes/badge.routes.js";
import certificateRoutes from "./domains/campus/certificates/presentation/routes/certificate.routes.js";
import skillRoutes from "./domains/career/skills/presentation/routes/skill.routes.js";
import portfolioProjectRoutes from "./domains/career/portfolio/presentation/routes/portfolio-project.routes.js";
import experienceRoutes from "./domains/career/experience/presentation/routes/experience.routes.js";
import educationRoutes from "./domains/career/education/presentation/routes/education.routes.js";
import certificationRoutes from "./domains/career/certifications/presentation/routes/certification.routes.js";
import achievementRoutes from "./domains/career/achievements/presentation/routes/achievement.routes.js";
import userPortfolioRoutes from "./domains/career/user-portfolio/presentation/routes/user-portfolio.routes.js";
import resumeRoutes from "./domains/career/resume/presentation/routes/resume.routes.js";
import companyRoutes from "./domains/placements/companies/presentation/routes/company.routes.js";
import placementDriveRoutes from "./domains/placements/drives/presentation/routes/placement-drive.routes.js";
import jobApplicationRoutes from "./domains/placements/applications/presentation/routes/job-application.routes.js";
import recruiterRoutes from "./domains/placements/recruiters/presentation/routes/recruiter.routes.js";
import interviewRoundRoutes from "./domains/placements/interviews/presentation/routes/interview-round.routes.js";
import assessmentRoutes from "./domains/academic/assessments/presentation/routes/assessment.routes.js";
import codingProfileRoutes from "./domains/career/coding-profiles/presentation/routes/coding-profile.routes.js";
import connectionRoutes from "./domains/community/connections/presentation/routes/connection.routes.js";
import attendanceRoutes from "./domains/academic/attendance/presentation/routes/attendance.routes.js";
import placementAnalyticsRoutes from "./domains/placements/analytics/presentation/routes/placement-analytics.routes.js";
import notificationRoutes from "./domains/communication/notifications/presentation/routes/notification.routes.js";
import newsRoutes from "./domains/communication/news/presentation/routes/news.routes.js";
import chatRoutes from "./domains/communication/chat/presentation/routes/chat.routes.js";
import messageRoutes from "./domains/communication/chat/presentation/routes/message.routes.js";
import aiChatRoutes from "./domains/ai/chat/presentation/routes/ai-chat.routes.js";
import resumeReviewRoutes from "./domains/ai/resume-review/presentation/routes/resume-review.routes.js";
import careerScoreRoutes from "./domains/ai/career-score/presentation/routes/career-score.routes.js";
import recommendationsRoutes from "./domains/ai/recommendations/presentation/routes/recommendations.routes.js";
import mockInterviewRoutes from "./domains/ai/interview/presentation/routes/mock-interview.routes.js";
import dashboardRoutes from "./domains/administration/dashboard/presentation/routes/dashboard.routes.js";

const app: Express = express();

bootstrap(app);

app.use("/api/v1/auth", authRoutes);
app.use("/api/v1/users", userRoutes);
app.use("/api/v1/invitations", invitationRoutes);
app.use("/api/v1/organizations/settings", organizationSettingsRoutes);
app.use("/api/v1/organizations", organizationRoutes);
app.use("/api/v1/activities", activityRoutes);
app.use("/api/v1/submissions",submissionRoutes);
app.use("/api/v1/audit-logs", auditLogRoutes);
app.use("/api/v1/departments", departmentRoutes);
app.use("/api/v1/faculty", facultyRoutes);
app.use("/api/v1/students", studentRoutes);
app.use("/api/v1/alumni", alumniRoutes);
app.use("/api/v1/mentorships", mentorshipRoutes);
app.use("/api/v1/clubs", clubRoutes);
app.use("/api/v1/events", eventRoutes);
app.use("/api/v1/leaderboard", leaderboardRoutes);
app.use("/api/v1/point-ledger", pointLedgerRoutes);
app.use("/api/v1/ai/provider", aiProviderStatusRoutes);
app.use("/api/v1/badges", badgeRoutes);
app.use("/api/v1/certificates", certificateRoutes);
app.use("/api/v1/skills", skillRoutes);
app.use("/api/v1/projects", portfolioProjectRoutes);
app.use("/api/v1/experience", experienceRoutes);
app.use("/api/v1/education", educationRoutes);
app.use("/api/v1/certifications", certificationRoutes);
app.use("/api/v1/achievements", achievementRoutes);
app.use("/api/v1/portfolio", userPortfolioRoutes);
app.use("/api/v1/resume", resumeRoutes);
app.use("/api/v1/companies", companyRoutes);
app.use("/api/v1/placements", placementDriveRoutes);
app.use("/api/v1/applications", jobApplicationRoutes);
app.use("/api/v1/recruiters", recruiterRoutes);
app.use("/api/v1/interview-rounds", interviewRoundRoutes);
app.use("/api/v1/assessments", assessmentRoutes);
app.use("/api/v1/coding-profiles", codingProfileRoutes);
app.use("/api/v1/connections", connectionRoutes);
app.use("/api/v1/attendance", attendanceRoutes);
app.use("/api/v1/placement-analytics", placementAnalyticsRoutes);
app.use("/api/v1/notifications", notificationRoutes);
app.use("/api/v1/news", newsRoutes);
app.use("/api/v1/chats", chatRoutes);
app.use("/api/v1/messages", messageRoutes);
app.use("/api/v1/ai/chat", aiChatRoutes);
app.use("/api/v1/ai/resume-review", resumeReviewRoutes);
app.use("/api/v1/ai/career-score", careerScoreRoutes);
app.use("/api/v1/ai/recommendations", recommendationsRoutes);
app.use("/api/v1/ai/interview", mockInterviewRoutes);
app.use("/api/v1/dashboard", dashboardRoutes);
app.use(notFound);

app.use(errorHandler);

export default app;