export enum Permission {

    // Organization
    MANAGE_ORGANIZATION = "MANAGE_ORGANIZATION",
    MANAGE_USERS = "MANAGE_USERS",
    MANAGE_DEPARTMENTS = "MANAGE_DEPARTMENTS",
    MANAGE_CLUBS = "MANAGE_CLUBS",

    // Academic
    CREATE_ACTIVITY = "CREATE_ACTIVITY",
    UPDATE_ACTIVITY = "UPDATE_ACTIVITY",
    DELETE_ACTIVITY = "DELETE_ACTIVITY",

    REVIEW_SUBMISSION = "REVIEW_SUBMISSION",

    VIEW_LEADERBOARD = "VIEW_LEADERBOARD",

    // Community
    CREATE_EVENT = "CREATE_EVENT",
    MANAGE_EVENTS = "MANAGE_EVENTS",
    SEND_NOTIFICATION = "SEND_NOTIFICATION",

    // Career
    MANAGE_PLACEMENTS = "MANAGE_PLACEMENTS",
    MANAGE_PROJECTS = "MANAGE_PROJECTS",

    // Alumni
    VERIFY_ALUMNI = "VERIFY_ALUMNI",

    // Analytics
    VIEW_ANALYTICS = "VIEW_ANALYTICS",

    // Platform
    MANAGE_PLATFORM = "MANAGE_PLATFORM"

}